
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tvtuttle
 */
public class BlackjackPanel extends javax.swing.JPanel {

    /**
     * Creates new form BlackjackPanel
     */
    DecisionGridFrame decisionGrid;
    int[] decisionSettings;
    public BlackjackPanel() {
        initComponents();
        decisionGrid = new DecisionGridFrame();
        decisionGrid.updateSettings();
        setVisible(true);
    }
    
//    public void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        g.fillOval(100,100,100,100);            // Just checking!
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        insuranceButton = new javax.swing.JToggleButton();
        numField = new javax.swing.JTextField();
        numLabel = new javax.swing.JLabel();
        chatterButton = new javax.swing.JToggleButton();
        numDecksLabel = new javax.swing.JLabel();
        numDecksField = new javax.swing.JTextField();
        numDecksSlider = new javax.swing.JSlider();

        setLayout(null);

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        add(playButton);
        playButton.setBounds(10, 170, 100, 23);

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 450, 96);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(10, 110, 100, 23);

        insuranceButton.setText("Insurance");
        add(insuranceButton);
        insuranceButton.setBounds(10, 80, 100, 23);

        numField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        numField.setText("1000");
        add(numField);
        numField.setBounds(200, 0, 100, 30);

        numLabel.setText("Number of Games to Simulate");
        add(numLabel);
        numLabel.setBounds(10, 0, 190, 20);

        chatterButton.setText("Chatter");
        add(chatterButton);
        chatterButton.setBounds(10, 140, 100, 23);

        numDecksLabel.setText("Number of Decks");
        add(numDecksLabel);
        numDecksLabel.setBounds(10, 40, 170, 20);

        numDecksField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        numDecksField.setText("1");
        numDecksField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDecksFieldActionPerformed(evt);
            }
        });
        add(numDecksField);
        numDecksField.setBounds(200, 40, 100, 30);

        numDecksSlider.setMaximum(8);
        numDecksSlider.setMinimum(1);
        numDecksSlider.setValue(1);
        numDecksSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numDecksSliderStateChanged(evt);
            }
        });
        add(numDecksSlider);
        numDecksSlider.setBounds(310, 40, 200, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        updateSettings();
        int profit = new Blackjack().play(Integer.parseInt(numField.getText()), decisionSettings, insuranceButton.isSelected(), chatterButton.isSelected(), numDecksSlider.getValue());
        outputArea.append(profit + " profit over " + numField.getText() + " games with expected profit " + (profit/Double.parseDouble(numField.getText())) + "\n");
    }//GEN-LAST:event_playButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateSettings();
        for (int i = 0; i < decisionSettings.length; i ++){
            System.out.print(decisionSettings[i]);
        }
        System.out.println("");
        System.out.println("decisionSettings.length = " + decisionSettings.length);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void numDecksFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDecksFieldActionPerformed
        // TODO add your handling code here:
        numDecksSlider.setValue(Integer.parseInt(numDecksField.getText()));
    }//GEN-LAST:event_numDecksFieldActionPerformed

    private void numDecksSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numDecksSliderStateChanged
        // TODO add your handling code here:
        numDecksField.setText("" + numDecksSlider.getValue());
    }//GEN-LAST:event_numDecksSliderStateChanged
    
    private void updateSettings(){
        decisionSettings = decisionGrid.updateSettings();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton chatterButton;
    private javax.swing.JToggleButton insuranceButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numDecksField;
    private javax.swing.JLabel numDecksLabel;
    private javax.swing.JSlider numDecksSlider;
    private javax.swing.JTextField numField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton playButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
